filetype off

silent! call pathogen#runtime_append_all_bundles()
silent! call pathogen#helptags()

filetype on                                                            " File extension detection switch
filetype plugin on
filetype indent on                                                     " type of file triggers the FileType event when set

colorscheme vibrantink                                                 " change the color scheme

syntax on                                                              " Turn on syntax highlighting

highlight WhitespaceEOL ctermbg=red guibg=red                          " Show trailing spaces
match WhitespaceEOL /\s\+$/

set sessionoptions=buffers,winsize                                     " What to save to sessions file
set nocompatible                                                       " Set to make sure we don't behave like vi but vim
set hidden                                                             " hides buffers instead of closing them
set ofu=syntaxcomplete#Complete                                        " Add autocomplete
set visualbell t_vb=                                                   " No audio or visual bell
set ts=2                                                               " number of spaces a <Tab> in the text stands for
set sw=2                                                               " number of spaces used for each step of (auto)indent
set sta                                                                " a <Tab> in an indent inserts 'shiftwidth' spaces
set si                                                                 " Smart indent
set ai                                                                 " automatically set the indent of a new line
set ar                                                                 " automatically read a file when it was modified outside of Vim
set ci                                                                 " Copy whitespace for indenting from previous line
set et                                                                 " Expand tab to spaces
set guifont=Monospace\ 10                                              " Change the font for gVim
set pastetoggle=<F2>                                                   " Paste toggle
set anti
set hi=1000                                                            " How many item to keep in history list
set hlsearch                                                           " highlight searches
set ignorecase                                                         " ignore case when searching
set is                                                                 " incremental searchshow match for partly typed search command
set laststatus=2                                                       " always display the status line
set number                                                             " Display line numbers
set nuw=1                                                              " Width of the line number carret
set ruler                                                              " show the cursor position all the time
set scs                                                                " override 'ignorecase' when pattern has upper case characters
set sel=inclusive                                                      " how selecting text behaves 'old', 'inclusive' or 'exclusive';
set showtabline=1                                                      " when to use a tab pages line. 0, 1 or 2;
set slm="mouse"                                                        " when to start Select mode instead of Visual mode 'mouse', 'key' and/or 'cmd';
set sm                                                                 " When inserting a bracket, briefly jump to its match
set sol                                                                " many jump commands move the cursor to the first non-blank
set sts=2                                                              " Number of spaces to insert for a tab
set title                                                              " show title in console title bar
set ttyfast                                                            " smoother changes
set ul=1000                                                            " Number of undos to keep
set cursorline
set nobackup                                                           " Don't backup
set noswapfile                                                         " Don't create swap files
set shellslash                                                         " Use forward slash when expanding file names
set nowrap                                                             " Lines don't wrap.
set autowrite                                                          " Automatic saving on file change
set autoread                                                           " Autoreload on file change
set encoding=utf-8                                                     " Character encoding / file encoding
set fileencoding=utf-8
set noequalalways                                                      " Without setting this, ZoomWin restores windows in a way that causes
                                                                       " equalalways behavior to be triggered the next time CommandT is used.
                                                                       " This is likely a bludgeon to solve some other issue, but it works
set wildignore+=gems/*,*.gif,*.py[co],.git,*.jpg,vendor/*,logs/*,log/* " Ignore gems directory of a project
set list                                                               " Show special characters
set listchars=tab:▸\ ,eol:¬,nbsp:.                                     " which special characters to use
set guioptions-=T                                                      " Start without the toolbar
set guioptions-=m                                                      " Remove menu bar

" let mapleader = ','                                                   " Change the Leader key
" let g:toggleTabs = 1                                                 " Display visual tabs when there is more than tab
let g:ctrlp_working_path_mode = 0                                      " Don't let ctrlp manage working directory
let g:ctrlp_match_window_bottom = 1                                    " Show ctrlp window at the top
let g:ctrlp_match_window_reversed = 0                                  " Show ctrlp matches at the top first


if has("gui_running")
  set statusline=
  set statusline+=%{fugitive#statusline()}\         "Git branch
  set statusline+=[%n]\                             "Buffer-Nummer
  set statusline+=%h                                "Help buffer flag [help]
  set statusline+=%w                                "Preview window flag [Preview]
  set statusline+=%m                                "Modified flag, [+] [-]
  set statusline+=%r                                "Readonly flag [RO]
  set statusline+=%<%.99f\                          "Am Anfang gekürzt, maximal 99 Zeichen, Dateiname (relativ)
  set statusline+=%y\                               "Dateityp, z.B [vim], [eruby], [Rails], …
  set statusline+=[%{strlen(&fenc)?&fenc:'none'}/   "Datei-Codierung, [utf-8]
  set statusline+=%{&ff}]                           "Datei-Format, [unix]
  set statusline+=%=                                "Links/Rechts Separator -----------------------
  set statusline+=Line:\ %l/%L\                     "Zeilennummer/Anzahl der Zeilen
  set statusline+=[%p%%]\                           "Prozentstand der Datei
  set statusline+=Column:\ %c-%v                    "Spaltennummer, Virtuelle Spaltennummer
  set statusline+=\ [%{FileSize()}]\                "Dateigröße
else
  set statusline=
  set statusline+=[%n]\                             "Buffer-Nummer
  set statusline+=%h                                "Help buffer flag [help]
  set statusline+=%w                                "Preview window flag [Preview]
  set statusline+=%m                                "Modified flag, [+] [-]
  set statusline+=%r                                "Readonly flag [RO]
  set statusline+=%<%.99f\                          "Am Anfang gekürzt, maximal 99 Zeichen, Dateiname (relativ)
  set statusline+=%y\                               "Dateityp, z.B [vim], [eruby], [Rails], …
  set statusline+=[%{strlen(&fenc)?&fenc:'none'}/   "Datei-Codierung, [utf-8]
  set statusline+=%{&ff}]                           "Datei-Format, [unix]
  set statusline+=%=                                "Links/Rechts Separator -----------------------
  set statusline+=Line:\ %l/%L\                     "Zeilennummer/Anzahl der Zeilen
  set statusline+=[%p%%]\                           "Prozentstand der Datei
  set statusline+=Column:\ %c-%v                    "Spaltennummer, Virtuelle Spaltennummer
  set statusline+=\ [%{FileSize()}]\                "Dateigröße
endif

" Control key mappings

" Recent Buffer Menu
nnoremap <C-Tab> :CtrlPMRU<CR>
inoremap <C-Tab> <ESC>:CtrlPMRU<CR>

" Control-][ to increase/decrease indentation
vmap <C-]> >gv
vmap <C-[> <gv

" commenting
vmap <silent> <C-/> <leader>c<space>
nmap <silent> <C-/> <leader>c<space>
imap <silent> <C-/> <esc><leader>c<space>

" Bubble single lines
imap <C-Up> <ESC>[e<ESC>i
nmap <C-Up> [e

imap <C-Down> <ESC>]e<ESC>i
nmap <C-Down> ]e

" Bubble multiple lines
vmap <C-Up> [egv
vmap <C-Down> ]egv

" Show open buffers
nmap <C-b> :CtrlPBuffer<cr>
imap <C-b> <esc>:CtrlPBuffer<cr>

" Copy
nmap <C-c> yy
imap <C-c> <esc>yy<esc>i
vmap <C-c> y

" Delete line
nmap <C-d> dd
imap <C-d> <esc>dd<esc>i

if has("gui_running")
  " find
  nmap <silent> <C-f> <ESC>:promptfind<CR>
  imap <silent> <C-f> <ESC>:promptfind<CR>

  " find and replace
  nmap <silent> <C-h> <ESC>:promptrepl<CR>
  imap <silent> <C-h> <ESC>:promptrepl<CR>
else
  " Search and replace
  imap <C-h> <esc>:%s/old/new/gc
  nmap <C-h> <esc>:%s/old/new/gc
endif

" SuperTab completion
"<C-n>

" Search through project fo file
nmap <C-p> :CtrlP<CR>
imap <C-p> <esc>:CtrlP<CR>

" Visual Block
" <C-q>

" saving
imap <C-s> <esc>:w<cr>a
nmap <C-s> :w<cr>

" Paste
nmap <C-v> p
imap <C-v> <esc>p<esc>i
vmap <C-v> p

" Close current buffer
nmap <C-w> :Bclose<CR>
imap <C-w> <esc>:Bclose<CR><esc>i

" Cut
nmap <C-x> dd
imap <C-x> <esc>dd<esc>i
vmap <C-x> d

" Undo
nmap <silent> <C-z> :undo<CR>
imap <silent> <C-z> <ESC>:undo<CR>i


" META key mappings

" Visual Mode
nmap <M-Up> v
imap <M-Up> <ESC>v
vmap <M-Up> v

nmap <M-Down> v
imap <M-Down> <ESC>v
vmap <M-Down> v

nmap <M-Left> v
imap <M-Left> <ESC>v
vmap <M-Left> v

nmap <M-Right> v
imap <M-Right> <ESC>v
vmap <M-Right> v

" Copy selected text into global buffer
vmap <M-c> "+ygv

" window split horizontal
nmap <M-h> :split<cr>
imap <M-h> <esc>:split<cr>

" execute a nerdtreefind
inoremap <M-l> <esc>:NERDTreeFind<cr>
nnoremap <M-l> <esc>:NERDTreeFind<cr>

" search through all files
nmap <M-f> :ack<space>
imap <M-f> <esc>:ack<space>

" Delete line
nmap <M-k> dd
imap <M-k> <esc>dd<esc>i

" Toggle NERDTree
nmap <M-n> :NERDTreeToggle<cr>
imap <M-n> <esc>:NERDTreeToggle<cr>

" Paste from global buffer
nmap <M-p> "+gP
imap <M-p> <ESC>"+gPa

" Close everything
nmap <M-q> :wqa<cr>
imap <M-q> <esc>:wqa<cr>

" Close current window
imap <M-w> <ESC>:q<CR>
nmap <M-w> :q<CR>

" large recent buffer ment
nnoremap <M-r> :MRU<cr>
inoremap <M-r> <esc>:MRU<cr>

" window split vertical
nmap <silent> <M-v> :vsplit<cr>
imap <silent> <M-v> <esc>:vsplit<cr>

" Load the last auto saved sessions
nmap <M-s> :so ~/.vim/sessions/autosession<CR>

" Cut selected text into global buffer
vmap <silent> <M-x> "+x

" Undo
nmap <silent> <M-z> :redo<CR>
imap <silent> <M-z> <ESC>:redo<CR>i



" Control + Shift mappings

" Window movement
nmap <silent> <CS-Up> :wincmd k<CR>
imap <silent> <CS-Up> :wincmd k<CR>

nmap <silent> <CS-Down> :wincmd j<CR>
imap <silent> <CS-Down> :wincmd j<CR>

nmap <silent> <CS-Left> :wincmd h<CR>
imap <silent> <CS-Left> :wincmd h<CR>

nmap <silent> <CS-Right> :wincmd l<CR>
imap <silent> <CS-Right> :wincmd l<CR>


" Leader mappings
" ZoomWin configuration
nmap <Leader><Leader> :ZoomWin<CR>
imap <Leader><Leader> :ZoomWin<CR>

" open up your .vimrc
nmap <Leader>ev :e ~/.vimrc<CR>

" Source (reload) .vimrc
nmap <Leader>sv :so ~/.vimrc<CR>

" clear highlight searchs
nmap <silent> <leader>/ :nohlsearch<cr>

" refresh all buffers from disk
nmap <leader>r :set noconfirm<cr>:bufdo e!<cr>:set confirm<cr>:syntax on<cr>

" Function key mappings

" Toggle set paste
" <F2>

" Yank Ring
noremap <F4> :YRShow<CR>

" Toggle Gundo list
nnoremap <F5> :GundoToggle<CR>

" Scratch Pad
" <F8>

if has("autocmd")
  augroup vimrc_autocmds
    " clear auto commands
    au!
    " Reload the .vimrc when it is saved
    autocmd bufwritepost .vimrc source $MYVIMRC

    " Remove trailing spaces when saving
    autocmd BufWritePre * :%s/\s\+$//e

    " Automatically save the state of vim when you close it down
    autocmd VimLeave * :!rm ~/.vim/sessions/autosession
    autocmd VimLeave * :mks ~/.vim/sessions/autosession

    " Start NERDTree in the home directory
    autocmd VimEnter * :cd ~
    autocmd VimEnter * :NERDTree

    autocmd VimEnter * set vb t_vb=
  augroup END
endif

function! FileSize()
  let bytes = getfsize(expand("%:p"))
  if bytes <= 0
    return ""
  endif
  if bytes < 1024
    return bytes . " B"
  elseif bytes < 1000000
    return (bytes / 1024) . " KB"
  else
    return (bytes / 1000000) . " MB"
  endif
endfunction
